In [3]:
!pip install tensorflow
!pip install matplotlib
!pip install numpy
!pip install pandas


  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 3.6 MB/s  0:00:023.7 MB/s eta 0:00:01:01
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 3.6 MB/s  0:00:003.7 MB/s eta 0:00:01
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [matplotlib] 5/6 [matplotlib]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 3.7 MB/s  0:00:02m 3.7 MB/s eta 0:00:01


In [4]:
import numpy as np
import matplotlib.pyplot as plt
import torch 
import warnings
warnings.filterwarnings("ignore")

In [14]:
# !pip show tensorflow

Name: tensorflow
Version: 2.20.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/pagupta/Desktop/GD_Projects/module_2_all_courses/ML_Specialization_coursera/ml_special_311/lib/python3.11/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google_pasta, grpcio, h5py, keras, libclang, ml_dtypes, numpy, opt_einsum, packaging, protobuf, requests, setuptools, six, tensorboard, termcolor, typing_extensions, wrapt
Required-by: 


In [9]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
# ! pip install --upgrade pip
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [22]:
# Forward Propogation  = > procedure from giving input to producing output , known as forward propogation.
# Backward propogation =>  calculate the loss and backpropogate this loss in the entire network for updation of the weights and minimize the loss and improve the efficiency of the network.
# Neurons : Neurons is the multiple nodes in network just like human brain that have their own weight and bias.they take input and producing the outputs.
# Layers: combination of multiple nodes at the same level known as layer.
# inference process: in an epoch we first give an input to the network and nwtowrk produce an output after thsis we calculate the loss and propogate this loss in the backward direction. so we can update the weigths. this procedure go further for multiple epochs and this is how model is train. 
# Numpy arrays v/s tensors
# Activation function: it is a simple mathematical function that scale output in between some specific range.

x=np.array([[200.0,17.0]],dtype=np.float32)
layer_1=Dense(units=3,activation='sigmoid')
a1=layer_1(x)
layer2=Dense(units=1,activation='sigmoid')
a2=layer2(a1)

model=Sequential([layer_1,layer2])







In [23]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (1, 3)                 │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (1, 1)                 │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
W1 = np.array([
    [-8.94,  0.29, 12.89],
    [-0.17, -7.34, 10.79]] )
b1 = np.array([-9.87, -9.28,  1.01])
W2 = np.array([
    [-31.38],
    [-27.86],
    [-32.79]])
b2 = np.array([15.54])

model=Sequential(
    [
        tf.keras.Input(shape=(2,)),
        Dense(units=3,activation='sigmoid',name='layer_1'),
        Dense(units=1,activation='sigmoid',name='layer_2')
        
    ]
)
    

In [30]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer_1 (Dense)                 │ (None, 3)              │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_2 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.get_weights()

[array([[ 0.6872287 ,  0.06619465, -0.83534205],
        [-0.06613064,  0.70062435,  0.91477084]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[0.57210016],
        [1.1363198 ],
        [0.16530955]], dtype=float32),
 array([0.], dtype=float32)]

In [32]:
model.get_layer('layer_1').set_weights([W1,b1])

In [33]:
model.get_layer('layer_2').set_weights([W2,b2])

In [34]:
model.get_weights()

[array([[-8.94,  0.29, 12.89],
        [-0.17, -7.34, 10.79]], dtype=float32),
 array([-9.87, -9.28,  1.01], dtype=float32),
 array([[-31.38],
        [-27.86],
        [-32.79]], dtype=float32),
 array([15.54], dtype=float32)]

In [36]:
#  AGI => Artificial general intelligence. (do anything a human can do)
# ANI => Artificial narrow intelligence. (self driving car,web search,smart speaker)

# vectorization => Vectorization in Python is a programming technique used to perform operations on entire arrays of data at once, rather than iterating through individual elements using explicit for loops. 

# model.compile =>   used to configure the model for training and evaluation. 

# model training step -> 
# 1.specify how to compute output given input x and parameters w,b.
# 2. specify loss and cost.
# 3. backpropogate the loss in network to update the weights.
# 3. train on data to minimize the loss J(w,b).
# for binary classificatuon probelm binarycrossentropyloss loss function is L(w,b)=> -ylog(y_hat)-(1-y)log(1-yhat)
# fro regression problem => we can use  mean_sqaured_error
# sigmoid: 1/(e**(-z)+1)
# relu : max(0,z)
# How to select activation function fro various probelm: 
# for regression problem : we can use either linear or relu.
# for classification problem : we can use sigmoid.
# for hidden layers recommended function is relu because it is fast compare to other function .
# why do we need activation function:
# for suppose if we do not use activation function just linear function (default) then model can not be able to fit complex patterns or data and would not be efficient. only linear function will produce the lonear output only so it can not solve the classification problems.

# for suppose if we use only linear function
# then a1=w1.x+b1
# a2=w2.a1+b2
# a2=w2.(w1.x+b1)+b2
# a2= w2.w1.x+w2.b1+b2
# similiar like a2=W.X+B
# which is a linear regreesion.




In [37]:
# Relu activation function :  
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LeakyReLU
from tensorflow.keras.activations import linear,relu,sigmoid


In [39]:
# multiclass classification problem: multiple classes like MNIST dataset classes 0,1,2,3,4,5,6,7,8,9
# for binary classification problem P(class_1)=x  and P(class_2)=1-x
# for not in the case of multiclass classification
# softmax:  use for multiclass classification problem . 
# z1=w1.x+b1
# z2=w2.x+b2
# z3=w3.x+b3
# z4=w4.x+b4
# z=np.array([z1,z2,z3,z4])
# P(a1)= np.exp(z1)/(np.sum(np.exp(z)))
# P(a4)= np.exp(z4)/(np.sum(np.exp(z)))
# P(a3)= np.exp(z3)/(np.sum(np.exp(z)))
# P(a2)= np.exp(z2)/(np.sum(np.exp(z)))


# loss L(a,y_hat)= -log(aj) if j in {1,....,9}


In [43]:
model=Sequential([
    Dense(units=25,activation='relu'),
    Dense(units=15,activation='relu'),
    Dense(units=10,activation='softmax'),
])

model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy())


In [44]:
x1=2.0/10000
x1

0.0002

In [45]:
x2= (1+1/10000)-(1-1/10000)
x2

0.00019999999999997797

In [46]:
# Numerical roundoff errors:
# for logisitic regression:  
# a=1/(1+np.exp(-z))
# loss= -ylog(a)-(1-y)log(1-a)
# loss= -y*log(1/(1+np.exp(-z)))-(1-y)*log(1-1/(1+np.exp(-z)))
# here we can face the roundoff eorrors;
# solution: 
# model.compile(loss=BinaryCrossentropy(from_logits=True))



# for softmax regression : 
# model.compile(loss=SparseCategoricalCrossentropy(from_logits=True))

# model=Sequential([
#     Dense(units=25,activation='relu'),
#     Dense(units=15,activation='relu'),
#     Dense(units=10,activation='linear'),
# ])

# model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))
# model.fit(X,y,epochs=100)
# logits=model(X)
# f_x=tf.nn.softmax()

# in last output layer instead of using softmax function we use linear function then apply softmax function on final outputs.



In [ ]:
# Advance optimization:
# gradient descent for optimization   wj= wj-alpha*J(w,b)
#gradient descent takes steps toward an local minima and these steps becomes smaller and smalles when it go towards local minima. because J(w,b) becomes minimum after eadcdh step. but the problem is that once the model reach local minima it can not be comes out . it stuck in local minima. because in multidimensional space we have multile minimias any local minimia can be a global minima. so if we stuck into one local minimax that is not global minima then we can not minimize the loss and  model will not be that efficient. that's why we introduce advance optimizers such as Adam that solve this problem.
# adam optimizer push the model and carry out this model from local minima to check whether there exits any global minima.
# it internally keeps increase the learning rate if stpes are to smaller. but if steps are larger then it reduce the alpha.

# model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3))



# additional layer type: like Convolution layer,flatten layer, if a layer is convolutional layer a node in this layer will not handle all inputs. it just handle only few inputs. inputs distributed among these nodes according to their weights.



In [47]:
import sympy

In [48]:
J,w=sympy.symbols('J,w')
J=w**2
J

w**2

In [51]:
dj_dw=sympy.diff(J,w)
dj_dw

2*w

In [53]:
dj_dw.subs([(w,2)])

4

In [ ]:
# evaluation of model : we divide the dataset into 3 parts training,validation and test data.
# model selection and training/cross validation/ test data; 


# Bias and variance: High bias(underfitting)  High variance(overfitting) 
# High bias training error is high as well as validation error is also high . underfitting : model does not work well on train as well as validation ataset.
# high variance training error is low but validation error is very high.  overfitting: model works well on training data but does not worl well on validation dataset.
#  complexity of the model increase (degree of model) then chances of overfitting also increase.
# regularization is the method to reduce the overfitting. it adds a panelty term lambda in cost function that controls the overfitting. if lambda is very large model will face underfitting because cost function becomes almost constant because all values becomes almost zero. 
# if lambda decrease then chances of overfitting increase.

# J(w,b) = np.sum(y_hat-y)**2/2m + lambda * np.sum(w**2)/2m
# bias and variance can not be high at the same time.


# how to reduce the overfitting:
# reduce the complexity , increase the regularization term, increase the size of training dataset , decrease the number of features
# how to reduce underfitting: increase the complexity, decrease the regularization term, increase the training data size, increase number of fearures.


# learning  curves:
# debugging a learing algorithm:
# get mpre training examples          fixes high variance
# try smaller sets of features        fixes high variance
# try getting additional features     fixes high bias
# try adding polynomial features      fixes high bias 
# try decreasing lambda               fixes high bias
# try increasing lambda               fixes high variance



In [ ]:
# Large neural network are low bias machines
# if model does not perfrom well on training set means it is high bias then use bigger and larger comples mnetwork.
# if yes then check for validation dataset if it does not perform well on validation set then use more and more data otherwise it is a good model.
#  if we go from simple network to complex netowrk then chances of overfitting increase but if we use good regularization value then we can prevent this.


# Unregulaized network:
# model=Sequential([
#     Dense(units=25,activation='relu'),
#     Dense(units=15,activation='relu'),
#     Dense(units=10,activation='linear'),
# ])

# Regularized network.
# model=Sequential([
#     Dense(units=25,activation='relu',kernel_regularizer=L2(0.01)),
#     Dense(units=15,activation='relu',kernel_regularizer=L2(0.01)),
#     Dense(units=10,activation='linear',kernel_regularizer=L2(0.01)),
# ])
# here lambda = 0.01




In [ ]:
# Process of Machine learning development
# 1. choose architecture(mode,data , hyperparameters etc)
# 2. train model
# 3. dignostics(bias,variance and error analysis)
# 4. again hyparameter tunning and jump to step 1.


# Addition of data
# data augmentation: modifying an existing training example to create a new training example. like rotating the image at different angles.changing the contrast,shrink the image, exapnd the image, mirror image, intorduce wraping, distortion. adding the noise to the speech also create new speech.
# data synthesis: using artificial data inputs to create a newtraining example.


    
# transfer learning : using data from a different task. we used a model that is already trained on similiar large size dataset. 
# DOWNLOAD NEUral network paraentrs pretrained on a larger dataset wth same input type.
# further train(fne tune) the network on your own data.


# Fairness , bias and ethics:
# bias : exihibit an unacceptable bias for example that discriinates agains women.


                            # actual class

                    # TRUE POSITIVE          FALSE POSITIVE
#predicted class    
                    # False negative            True negative 


# precision =  True positives/(true positive + False positive)
# recall = True positive /(True positive + False negative)

# using threshold in logisitce regression we can make tradeoff between precison and recall.
#  higher precison but  lower recall  and vice versa,
# high threshold mean high precision and less threshold means hig recall.
# f(w,b)>=threshold yhat=1
# f(w,b)<threshold yhat=0

# F1-score:  2*(recall * precision)/(recall+precision)
# if we are not able to decide which algorithm to choose then we can calculate the F1-score and algorithm that have high score we can go with that.

