In [1]:
# Broadcasting

# !pip install numpy
# !pip install pandas
# !pip install matplotlib
# !pip install scipy
# !pip install tensorflow




  Using cached numpy-2.4.2-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
Using cached numpy-2.4.2-cp311-cp311-macosx_14_0_arm64.whl (5.5 MB)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
  Using cached pandas-3.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Using cached pandas-3.0.1-cp311-cp311-macosx_11_0_arm64.whl (9.9 MB)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
  Using cached matplotlib-3.10.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (52 kB)
  Using cached contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.61.1-cp311-cp311-macosx_10_9_universal2.whl.metadata (114 kB)
  Using cached kiwisolver-1.4.9-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.3 kB)
  Using cached pillow-12.1.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.8 kB

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow

In [2]:
A=np.array([[56,0,4.4,68],[1.2,104,52,8],[1.8,135,99,0.9]],dtype=np.float32)
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]], dtype=float32)

In [4]:
cal=A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9], dtype=float32)

In [5]:
cal.reshape(1,4)
cal

array([ 59. , 239. , 155.4,  76.9], dtype=float32)

In [6]:
percentage=100*A/cal.reshape(1,4)
print(percentage)

[[94.91525    0.         2.831403  88.42653  ]
 [ 2.0338984 43.514645  33.462036  10.403121 ]
 [ 3.0508475 56.485355  63.706566   1.170351 ]]


In [8]:
a=np.random.randn(2,3)
b=np.random.randn(2,1)
c=a+b
c.shape

(2, 3)

In [9]:
a=np.array([[2,1],[1,3]])
np.dot(a,a)

array([[ 5,  5],
       [ 5, 10]])

In [ ]:
# BackPropogation algorithm:

# at output layer:
# del5= yhat*(1-yhat)*(y-yhat)

# at hidden layer
# del3 : y3*(1-y3)*(w13*del5)
# del4 : y4*(1-y4)*(w14*del5)
# del_w13=learning_rate*del5*y3
# del_w14=lr*del5*y4
# w13=w13+del_w13
# w14=w14+del_w14

# at input layer
# del_w11=lr*del3*x1
# del_w12=lr*del4*x1
# del_w21=lr*del3*x2
# del_w22=lr*del4*x2
# w11=w11+del_w11
# w12=w12+del_w12
# w13=w13+del_w13
# w14=w14+del_w14



# What if we initialize the weights to zero:
# it causes all neurons in a given layer to compute the exact same function , preventing the netowrk from learning meaningfull patterns through backpropogation. This is also known as symmetric weights or dead neuron problem.
# Ways to initialize the weights:
# random initialization
# Xavier/Glorot initialization adjust the scale of random based on the number of input and output connections of the layer to maintain variance of activations through the network.

# He initialization: similiar to xavier but optimized for layers using the ReLU activation.


# we should initialize the weights with very small values.in case of tanh or sigmoid functions if the weights are too large when we compute the activation values some values of z will be either very large or very small. and we more likely end up at these flat parts of the tanh where the slope of the gradient is very small and gradient descent will be very slow.
#  
# w=np.random.randn((3,2))*0.01

# Hyperparameters:
# learning rate , number of iteration,number of hidden layers and nodes in hidden layers,choice of activation,momentum ,mini batch size,etc.









In [ ]:
import numpy as np
class NeuralNetwork:
    def __init__(self,input_size,hidden_size,output_size):
        self.input_size=input_size
        self.output_size=output_size
        self.hidden_size=hidden_size

        self.weights_input_hidden=np.random.randn(self.input_size,self.hidden_size)
        self.weights_hidden_output=np.random.randn(self.hidden_size,self.output_size)

        self.bias_hidden=np.zeros((1,self.hidden_size))
        self.bias_output=np.zeros((1,self.output_size))

    def sigmoid(self,x):
        return 1/(1+np.exp(-x))

    def sigmoid_derivative(self,x):
        return x*(1-x)


    def feedforward(self,X):
        self.hidden_activation=np.dot(X,self.weights_input_hidden)+self.bias_hidden
        self.hidden_output=self.sigmoid(self.hidden_activation)
        self.output_activation=np.dot(self.hidden_output,self.weights_hidden_output)+self.bias_output
        self.predict_output=self.sigmoid(self.output_activation)
        return self.predict_output

    def backward(self,X,y,lr):
        output_error=y-self.predict_output
        output_delta=output_error*self.sigmoid_derivative(self.predict_output)
        hidden_error=np.dot(output_delta,self.weights_hidden_output.T)
        hidden_delta=hidden_error*self.sigmoid(self.hidden_output)
        self.weights_hidden_output+=np.dot(self.hidden_output.T,output_delta)*lr
        self.bias_output+=np.sum(output_delta,axis=0,keepdims=True)*lr
        self.weights_input_hidden+=np.dot(X.T,hidden_delta)*lr
        self.bias_hidden+=np.sum(hidden_delta,axis=0,keepdims=True)*lr

    
    def train(self,X,y,epochs,lr):
        for epoch in range(epochs):
            output=self.feedforward(X)
            self.backward(X,y,lr)
            if epoch%40==0:
                loss=np.mean(np.square(y-output))
                print(f"Epoch {epoch}, Loss:{loss}")


        
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

nn=NeuralNetwork(input_size=3,hidden_size=4,output_size=1)
nn.train(X,y,epochs=1000,lr=0.001)
output=nn.feedforward(X)
print(output)


# Neural Networks & Deep Learning — Study Notes

---

## 1. NumPy Broadcasting

Broadcasting allows NumPy to perform arithmetic on arrays of different shapes without explicit loops.

### Example — Nutrient Percentage Calculator

```python
import numpy as np

# 3x4 matrix: rows = nutrients, cols = food items
A = np.array([[56,  0,   4.4, 68 ],
              [1.2, 104, 52,  8  ],
              [1.8, 135, 99,  0.9]], dtype=np.float32)

# Sum each column (axis=0)
cal = A.sum(axis=0)              # shape (4,)

# Broadcast: divide each row by column totals
percentage = 100 * A / cal.reshape(1, 4)
print(percentage)
```

### Broadcasting Rules in Practice

```python
a = np.random.randn(2, 3)   # shape (2, 3)
b = np.random.randn(2, 1)   # shape (2, 1)
c = a + b                   # b is broadcast across columns → shape (2, 3)
```

NumPy stretches the smaller array along dimensions of size 1 to match the larger array — no data is copied.

---

## 2. Matrix Multiplication with NumPy

```python
a = np.array([[2, 1],
              [1, 3]])

np.dot(a, a)   # Matrix product A²
```

`np.dot` performs true matrix multiplication (not element-wise). Always prefer it over the `*` operator for dot products and matrix operations.

---

## 3. Backpropagation Algorithm

Backprop propagates the error from the output layer backwards through the network, adjusting each weight by its contribution to the error.

### Output Layer

```
δ₅  = ŷ · (1 − ŷ) · (y − ŷ)          ← error signal at output
```

### Hidden Layer

```
δ₃  = y₃ · (1 − y₃) · (w₁₃ · δ₅)     ← error signal for hidden node 3
δ₄  = y₄ · (1 − y₄) · (w₁₄ · δ₅)     ← error signal for hidden node 4
```

### Weight Updates — Hidden → Output

```
Δw₁₃ = lr · δ₅ · y₃  →  w₁₃ = w₁₃ + Δw₁₃
Δw₁₄ = lr · δ₅ · y₄  →  w₁₄ = w₁₄ + Δw₁₄
```

### Weight Updates — Input → Hidden

```
Δw₁₁ = lr · δ₃ · x₁  →  w₁₁ = w₁₁ + Δw₁₁
Δw₁₂ = lr · δ₄ · x₁  →  w₁₂ = w₁₂ + Δw₁₂
Δw₂₁ = lr · δ₃ · x₂  →  w₂₁ = w₂₁ + Δw₂₁
Δw₂₂ = lr · δ₄ · x₂  →  w₂₂ = w₂₂ + Δw₂₂
```

---

## 4. Weight Initialisation

### Problem: Zero Initialisation

If all weights are set to zero, every neuron in a layer computes the **exact same function** — gradients are identical and weights update identically forever. The network never breaks symmetry and learns nothing. This is called the **symmetric weights / dead neuron problem**.

### Initialisation Strategies

| Strategy | Formula | Best for |
|----------|---------|---------|
| **Random (small values)** | `W = np.random.randn(n_in, n_out) * 0.01` | General use |
| **Xavier / Glorot** | `W *= √(1 / n_in)` | Sigmoid / Tanh |
| **He Initialisation** | `W *= √(2 / n_in)` | ReLU |

> **Why small values matter:** Large initial weights push z = W·x + b into the flat saturation zones of sigmoid/tanh, where gradients ≈ 0 and learning stalls.

```python
# He initialisation example
W = np.random.randn(n_out, n_in) * np.sqrt(2 / n_in)
```

---

## 5. Hyperparameters

Key hyperparameters to tune in a neural network:

| Hyperparameter | Role |
|----------------|------|
| **Learning rate (α)** | Step size for gradient descent |
| **Number of iterations** | How long to train |
| **Number of hidden layers** | Depth of the network |
| **Nodes per hidden layer** | Width at each layer |
| **Activation function** | Non-linearity choice (ReLU, tanh, sigmoid) |
| **Momentum (β)** | Smoothing factor for gradient updates |
| **Mini-batch size** | Trade-off between speed and stability |

---

## 6. Neural Network — From-Scratch Implementation

A fully working 2-layer neural network built with NumPy, trained on the XOR problem.

### Architecture

```
Input (2) → Hidden Layer (4, sigmoid) → Output (1, sigmoid)
```

### Full Implementation

```python
import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # Weight matrices initialised randomly
        self.W1 = np.random.randn(input_size, hidden_size)
        self.W2 = np.random.randn(hidden_size, output_size)
        # Biases initialised to zero
        self.b1 = np.zeros((1, hidden_size))
        self.b2 = np.zeros((1, output_size))

    # ── Activation ────────────────────────────────────────────────────────
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    # ── Forward Pass ───────────────────────────────────────────────────────
    def feedforward(self, X):
        self.z1   = np.dot(X, self.W1) + self.b1     # linear: input → hidden
        self.a1   = self.sigmoid(self.z1)             # activation: hidden
        self.z2   = np.dot(self.a1, self.W2) + self.b2  # linear: hidden → output
        self.a2   = self.sigmoid(self.z2)             # activation: output (ŷ)
        return self.a2

    # ── Backward Pass ──────────────────────────────────────────────────────
    def backward(self, X, y, lr):
        # Output layer error
        output_error = y - self.a2
        output_delta = output_error * self.sigmoid_derivative(self.a2)

        # Hidden layer error
        hidden_error = np.dot(output_delta, self.W2.T)
        hidden_delta = hidden_error * self.sigmoid_derivative(self.a1)

        # Update weights and biases
        self.W2 += np.dot(self.a1.T, output_delta) * lr
        self.b2 += np.sum(output_delta, axis=0, keepdims=True) * lr
        self.W1 += np.dot(X.T, hidden_delta) * lr
        self.b1 += np.sum(hidden_delta, axis=0, keepdims=True) * lr

    # ── Training Loop ──────────────────────────────────────────────────────
    def train(self, X, y, epochs, lr):
        for epoch in range(epochs):
            output = self.feedforward(X)
            self.backward(X, y, lr)
            if epoch % 40 == 0:
                loss = np.mean(np.square(y - output))
                print(f"Epoch {epoch}, Loss: {loss:.6f}")
```

### Training on XOR

```python
# XOR dataset
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0], [1], [1], [0]])

nn = NeuralNetwork(input_size=2, hidden_size=4, output_size=1)
nn.train(X, y, epochs=1000, lr=0.1)

predictions = nn.feedforward(X)
print(predictions)
```

---

## 7. Forward & Backward Pass — Step by Step

### Forward Pass

```
X  →  Z1 = X · W1 + b1  →  A1 = σ(Z1)  →  Z2 = A1 · W2 + b2  →  A2 = σ(Z2) = ŷ
```

### Loss (MSE)

```
L = (1/m) · Σ (y − ŷ)²
```

### Backward Pass (Chain Rule)

```
∂L/∂W2 = A1ᵀ · δ₂          where  δ₂ = (y − ŷ) · σ'(ŷ)
∂L/∂W1 = Xᵀ  · δ₁          where  δ₁ = (δ₂ · W2ᵀ) · σ'(A1)
```

Each weight update: **W ← W + lr · ∂L/∂W**

---

## 8. Activation Functions

| Function | Formula | Range | Use case |
|----------|---------|-------|----------|
| **Sigmoid** | 1 / (1 + e⁻ˣ) | (0, 1) | Binary output layer |
| **Tanh** | (eˣ − e⁻ˣ) / (eˣ + e⁻ˣ) | (−1, 1) | Hidden layers (zero-centred) |
| **ReLU** | max(0, x) | [0, ∞) | Most hidden layers ✅ |
| **Leaky ReLU** | max(0.01x, x) | (−∞, ∞) | Avoids dying ReLU |
| **Softmax** | eˣⁱ / Σeˣʲ | (0, 1), sums to 1 | Multi-class output layer |

> **Sigmoid/tanh saturation problem:** For large \|z\| the gradient → 0, causing vanishing gradients. ReLU avoids this in the positive range.

---

## Quick Reference

```
Network depth     →  more hidden layers = more abstract features
Network width     →  more units per layer = more capacity
Learning rate     →  too high = diverge; too low = slow convergence
Batch size        →  larger = smoother gradients; smaller = more noise (regularising)
Weight init       →  small random values; use He for ReLU, Xavier for tanh/sigmoid
```

---
