In [6]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [7]:
torch.tensor([1,2,3],dtype=float)


tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
x=torch.tensor([3],dtype=torch.float32,requires_grad=True)
y=x**2


In [28]:
y.backward()

In [31]:
x.grad

tensor([6.])

In [88]:
import torch.nn as nn
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
        

    def forward(self,features):
        out=self.network(features)
        return out
    

    
    
        

    

In [89]:

features=torch.rand(10,5)
model=Model(5)



In [90]:
y_true = torch.randint(0,2,(10,1)).float()
y_pred=model(features)
y_pred.shape

torch.Size([10, 1])

In [91]:

eps = 1e-7

loss = -(y_true * torch.log(y_pred + eps) +
         (1 - y_true) * torch.log(1 - y_pred + eps))
loss

tensor([[0.5867],
        [0.6026],
        [0.7945],
        [0.8199],
        [0.7735],
        [0.5821],
        [0.6258],
        [0.5827],
        [0.6064],
        [0.6200]], grad_fn=<NegBackward0>)

In [92]:
model.linear1.bias

AttributeError: 'Model' object has no attribute 'linear1'

In [93]:
!pip install torchinfo

In [94]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
nn.Loss